{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "channel",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vpoojflbind6vdb2xcq2uhoddi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "channel-0.1.0.jar",
          "url": "channel-0.1.0.jar",
          "size": 9493,
          "sha512": "7688aec64773b2440883c6ff86dc6134b204dd84d025ae9dbce56afc1fceb1f2319ef1751fd5178138f2938dfd5092cd2c614da7ceb0fa83b3aa0c8c858188ae",
          "sha256": "4b29e855652186448f91b243e022e69b13e3d6be2635097fa72d4027fe5e5b0b",
          "sha1": "0dfdfedf9323a2319029bfa6af7f27384576ac6c",
          "md5": "714a64377b2a59ca3bdc0d7409973b75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "channel-0.1.0.jar",
          "url": "channel-0.1.0.jar",
          "size": 9493,
          "sha512": "7688aec64773b2440883c6ff86dc6134b204dd84d025ae9dbce56afc1fceb1f2319ef1751fd5178138f2938dfd5092cd2c614da7ceb0fa83b3aa0c8c858188ae",
          "sha256": "4b29e855652186448f91b243e022e69b13e3d6be2635097fa72d4027fe5e5b0b",
          "sha1": "0dfdfedf9323a2319029bfa6af7f27384576ac6c",
          "md5": "714a64377b2a59ca3bdc0d7409973b75"
        }
      ]
    }
  ]
}
